# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.17_ckpt500 --model ../n-tulu-ppo-jax/ckpt/v1.17_ckpt500 --save_dir outputs/v1.17_ckpt500/tydiqa_goldp_1shot
# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.17_ckpt500 --model ../n-tulu-ppo-jax/ckpt/v1.17_ckpt500 --save_dir outputs/v1.17_ckpt500/tydiqa_no_context_1shot

# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.17_ckpt999 --model ../n-tulu-ppo-jax/ckpt/v1.17_ckpt999 --save_dir outputs/v1.17_ckpt999/tydiqa_goldp_1shot
# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.17_ckpt999 --model ../n-tulu-ppo-jax/ckpt/v1.17_ckpt999 --save_dir outputs/v1.17_ckpt999/tydiqa_no_context_1shot


# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.18_ckpt500 --model ../n-tulu-ppo-jax/ckpt/v1.18_ckpt500 --save_dir outputs/v1.18_ckpt500/tydiqa_goldp_1shot
# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.18_ckpt500 --model ../n-tulu-ppo-jax/ckpt/v1.18_ckpt500 --save_dir outputs/v1.18_ckpt500/tydiqa_no_context_1shot

# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.18_ckpt999 --model ../n-tulu-ppo-jax/ckpt/v1.18_ckpt999 --save_dir outputs/v1.18_ckpt999/tydiqa_goldp_1shot
# python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.18_ckpt999 --model ../n-tulu-ppo-jax/ckpt/v1.18_ckpt999 --save_dir outputs/v1.18_ckpt999/tydiqa_no_context_1shot


python -m eval.bbh.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/bbh --max_num_examples_per_task 40 --no_cot --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --save_dir outputs/v1.19_ckpt200/bbh_direct
python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --save_dir outputs/v1.19_ckpt200/tydiqa_goldp_1shot
python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt200 --save_dir outputs/v1.19_ckpt200/tydiqa_no_context_1shot

python -m eval.bbh.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/bbh --max_num_examples_per_task 40 --no_cot --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --save_dir outputs/v1.19_ckpt400/bbh_direct
python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --save_dir outputs/v1.19_ckpt400/tydiqa_goldp_1shot
python -m eval.tydiqa.run_eval --use_chat_format --chat_formatting_function eval.templates.create_prompt_with_tulu_chat_format --data_dir data/eval/tydiqa --no_context --n_shot 1 --max_num_examples_per_lang 100 --max_context_length 512 --tokenizer_name_or_path ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --model ../n-tulu-ppo-jax/ckpt/v1.19_ckpt400 --save_dir outputs/v1.19_ckpt400/tydiqa_no_context_1shot
